language: node_js
node_js:
  - lts/*
notifications:
  email: false
services:
  - docker
sudo: false
dist: trusty
before_script:
  - echo 'Europe/London' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - chmod +x ./tools/test
before_install:
  - export TZ=Europe/London
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
  - travis_retry npm install
  - npm install -g snyk
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t tymly-base .
  - snyk auth ${SNYK_TOKEN}
  - snyk test --docker tymly-base
  - ./tools/test
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master