language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
sudo: false
dist: trusty
services: docker

stages:
  - Test
  - Release

jobs:
  include:
    - &tests
      stage: Test
      name: "Boot testing"
      if: (branch = master AND commit_message =~ /(feat|fix|perf|ci|build)\(?\w*\)?:/) OR (branch =~ /(dependabot)(?:.*)/ AND commit_message =~ /(build)\(?\w*\)?:/)
      before_script: chmod +x ./tools/test
      sctipt:
        - docker build -t tymly-base .
        - ./tools/test
    - <<: *tests
      name: "Snyk testing"
      if: (branch = master AND commit_message =~ /(feat|fix|perf|ci|build)\(?\w*\)?:/) OR (branch =~ /(dependabot)(?:.*)/ AND commit_message =~ /(build)\(?\w*\)?:/)
      install:
        - npm install -g snyk
      script:
        - docker build -t tymly-base .
        - snyk auth ${SNYK_TOKEN}
        - snyk test --docker tymly-base
    - stage: Release
      name: "Release Tymly Base"
      if: (branch = master AND commit_message =~ /(feat|fix|perf|ci|build)\(?\w*\)?:/) OR (branch = master AND commit_message =~ /(Merge pull request)(.*)(from wmfs\/dependabot)(.*)/)
      install:
        - npm install
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" #Docker login
        - docker build -t wmfs/tymly-base .
        - npx semantic-release