language: node_js
node_js:
  - 9
notifications:
  email: false
services:
  - docker
sudo: false
dist: trusty
env:
  global:
    - TAG=${TRAVIS_TAG}
before_script:
  - echo 'Europe/London' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - chmod +x ./tools/test
before_install:
  - export TZ=Europe/London
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
install:
  - travis_retry npm install
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t tymly-base .
  - ./tools/test
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: docker tag tymly-base wmfs/tymly-base && docker tag tymly-base wmfs/tymly-base:$TAG && docker push wmfs/tymly-base && docker push wmfs/tymly-base:$TAG
    on:
      tags: true