version: 2
jobs:
  test:
    docker:
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: chmod
        command: chmod +x ./tools/test
    - run:
        name: build
        command: docker build -t tymly-base .
    - run:
        name: test
        command: ./tools/test
  vulnerability:
    docker:
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_direcotry: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: vulnerability-db
    - run:
        name: build image
        command: docker build -t tymly-base .
    - run:
        name: install trivy
        command: |
          VERSION=%(
              curl --silent "https://api.github.com/repos/knqyf263/trivy/releases/latest" | \
              grep '"tag_name":' | \
              sed -E 's/.*"v([^"]+)".*/\1/'
          )
          wget https://github.com/knqyf263/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
          mv trivy /usr/local/bin
    - run:
        name: scan
        command: |
          ./trivy --quiet --auto-refresh --clear-cache tymly-base
          ./trivy --exit-code 1 --severity CRITICAL --quiet --clear-cache --auto-refresh tymly-base
    - save_cache:
        key: vulnerability-db
        paths:
          - $HOME/.cache/trivy
  release:
    docker:
    # use node:lts
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: install
        command: npm install
    - run:
        name: release
        command: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t wmfs/tymly-base .
          npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
    - test
    - vulnerability
    - release:
        requires:
        - test
        - vulnerability
        filters:
          branches:
            only: master

