version: 2
jobs:
  test:
    docker:
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build image
        command: docker build -t tymly-base .
    - run:
        name: pull postgres
        command: docker pull postgres:9.6.12-alpine
    - run:
        name: test build boot
        command: |
          docker-compose up &
          sleep 30
          tymly_up=$(docker logs repo_tymly_1 2>&1 | grep "Done booting.")
          if ! [ "$tymly_up" ]; then
              echo "Tymly is not running"
              exit 1
          fi
          if [ "$tymly_up" ]; then
              echo "Tymly is running"
          fi
  vulnerability:
    docker:
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_direcotry: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: vulnerability-db
    - run:
        name: build image
        command: docker build -t tymly-base .
    - run:
        name: scan image
        command: |
          wget https://github.com/knqyf263/trivy/releases/download/v0.1.2/trivy_0.1.2_Linux-64bit.tar.gz
          tar zxvf trivy_0.1.2_Linux-64bit.tar.gz
          ./trivy --quiet --auto-refresh --clear-cache tymly-base
          ./trivy --exit-code 1 --severity CRITICAL --quiet --clear-cache --auto-refresh tymly-base
    - save_cache:
        key: vulnerability-db
        paths:
          - $HOME/.cache/trivy
  release:
    docker:
    # use node:lts
    - image: circleci/node:lts
      environment:
        TZ: "Europe/London"
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: install
        command: npm install
    - run:
        name: release image
        command: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker build -t wmfs/tymly-base .
          npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
    - test
    - vulnerability
    - release:
        requires:
        - test
        - vulnerability
        filters:
          branches:
            only: master

