#!/usr/bin/env bash

docker-compose version

docker pull postgres:9.6.12-alpine

# Start Tymly Docker
echo "Lets test Tymly"

docker-compose up &

sleep 60

tymly_up=$(docker logs tymlybase_tymly_1 2>&1 | grep "Admin token")


# Check Tymly
echo "Check if Tymly is running, let us know if something isn't working"

if ! [ "$tymly_up" ]; then
    echo "Tymly is not running"
fi

if [ "$tymly_up" ]; then
    echo "Tymly is running"
fi

# Stop Tymly
echo "Take down the containers"

docker-compose down

if ! [ "$tymly_up" ] ; then
   exit 1
fi